#!/usr/bin/env python3
"""Sync root workflows into Claude Code command files.

This script keeps `commands/*.md` aligned with `workflows/*.md` while preserving
the project command contract:
  - canonical: run <workflow-name>
  - alias: /<workflow-name>
  - nested call token inside docs: Call /<workflow-name>
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

GENERATED_MARKER = "<!-- GENERATED BY: migrate_workflows_to_commands.py -->"

FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n?", re.DOTALL)


def safe_rel(path: Path, base: Path) -> str:
    try:
        return str(path.relative_to(base))
    except ValueError:
        return str(path)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Migrate workflows/*.md into commands/*.md command mirrors."
    )
    parser.add_argument(
        "--source-dir",
        default="workflows",
        help="Directory with workflow markdown files (default: workflows).",
    )
    parser.add_argument(
        "--target-dir",
        default="commands",
        help="Directory for generated command markdown files (default: commands).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned changes without writing files.",
    )
    parser.add_argument(
        "--prune",
        action="store_true",
        help="Remove stale generated commands that have no matching workflow.",
    )
    return parser.parse_args()


def split_frontmatter(content: str) -> tuple[str | None, str]:
    match = FRONTMATTER_RE.match(content)
    if not match:
        return None, content
    return match.group(1), content[match.end() :]


def extract_description(frontmatter: str | None) -> str:
    if not frontmatter:
        return "Workflow command mirror."
    for raw_line in frontmatter.splitlines():
        line = raw_line.strip()
        if line.startswith("description:"):
            return line.split(":", 1)[1].strip().strip('"').strip("'")
    return "Workflow command mirror."


def build_command_content(
    *,
    workflow_name: str,
    workflow_rel_path: str,
    workflow_body: str,
    workflow_description: str,
) -> str:
    body = workflow_body.strip() + "\n"
    return (
        f"{GENERATED_MARKER}\n"
        "---\n"
        f"description: {workflow_description}\n"
        f"source_workflow: {workflow_rel_path}\n"
        "compatibility:\n"
        f"  canonical: \"run {workflow_name}\"\n"
        f"  slash: \"/{workflow_name}\"\n"
        f"  nested: \"Call /{workflow_name}\"\n"
        "---\n\n"
        f"# Command: {workflow_name}\n\n"
        "## Compatibility Contract\n"
        f"- Canonical form: `run {workflow_name}`\n"
        f"- Slash alias: `/{workflow_name}`\n"
        f"- Nested reference token: `Call /{workflow_name}`\n\n"
        "## Synced Workflow Body\n"
        "The content below is synchronized from the source workflow.\n\n"
        f"{body}"
    )


def build_run_router_content(index_rel_path: str) -> str:
    return (
        f"{GENERATED_MARKER}\n"
        "---\n"
        "description: Canonical workflow router (run <workflow-name>)\n"
        f"index_file: {index_rel_path}\n"
        "---\n\n"
        "# Command: run\n\n"
        "## Purpose\n"
        "Compatibility wrapper for canonical workflow invocation form `run <workflow-name>`.\n\n"
        "## Contract\n"
        "1. Parse the first argument as `<workflow-name>`.\n"
        "2. Open `commands/_workflow_index.json` and resolve the command entry.\n"
        "3. Execute the resolved command body from `commands/<workflow-name>.md`.\n"
        "4. If command is not found, return an explicit error and print available names.\n\n"
        "## Notes\n"
        "- This file is a routing contract for Claude Code command mode.\n"
        "- Source workflows remain in `workflows/` and are synchronized via migration script.\n"
    )


def write_text(path: Path, content: str, dry_run: bool) -> str:
    if not path.exists():
        if dry_run:
            return "create"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return "create"

    current = path.read_text(encoding="utf-8")
    if current == content:
        return "unchanged"

    if dry_run:
        return "update"
    path.write_text(content, encoding="utf-8")
    return "update"


def main() -> int:
    args = parse_args()
    script_root = Path(__file__).resolve().parent.parent
    source_dir = (script_root / args.source_dir).resolve()
    target_dir = (script_root / args.target_dir).resolve()

    if not source_dir.is_dir():
        print(f"[ERROR] Source directory not found: {source_dir}", file=sys.stderr)
        return 1

    workflows = sorted(p for p in source_dir.glob("*.md") if p.is_file())
    if not workflows:
        print(f"[ERROR] No workflow files found in: {source_dir}", file=sys.stderr)
        return 1

    if not args.dry_run:
        target_dir.mkdir(parents=True, exist_ok=True)

    created = 0
    updated = 0
    unchanged = 0
    deleted = 0

    index_entries: list[dict[str, str]] = []
    expected_command_names: set[str] = set()

    for workflow_path in workflows:
        workflow_name = workflow_path.stem
        expected_command_names.add(workflow_name)
        workflow_rel = safe_rel(workflow_path, script_root)
        content = workflow_path.read_text(encoding="utf-8")
        frontmatter, body = split_frontmatter(content)
        description = extract_description(frontmatter)
        command_content = build_command_content(
            workflow_name=workflow_name,
            workflow_rel_path=workflow_rel,
            workflow_body=body,
            workflow_description=description,
        )

        command_path = target_dir / f"{workflow_name}.md"
        status = write_text(command_path, command_content, args.dry_run)
        if status == "create":
            created += 1
        elif status == "update":
            updated += 1
        else:
            unchanged += 1

        index_entries.append(
            {
                "name": workflow_name,
                "source_workflow": workflow_rel,
                "command_file": safe_rel(command_path, script_root),
                "canonical": f"run {workflow_name}",
                "slash": f"/{workflow_name}",
                "nested": f"Call /{workflow_name}",
            }
        )

    index_entries.sort(key=lambda entry: entry["name"])
    index_path = target_dir / "_workflow_index.json"
    index_content = json.dumps(
        {
            "source_dir": safe_rel(source_dir, script_root),
            "target_dir": safe_rel(target_dir, script_root),
            "workflow_count": len(index_entries),
            "workflows": index_entries,
        },
        ensure_ascii=False,
        indent=2,
    ) + "\n"
    idx_status = write_text(index_path, index_content, args.dry_run)
    if idx_status == "create":
        created += 1
    elif idx_status == "update":
        updated += 1
    else:
        unchanged += 1

    run_router_path = target_dir / "run.md"
    run_router_content = build_run_router_content(
        index_rel_path=safe_rel(index_path, script_root)
    )
    run_status = write_text(run_router_path, run_router_content, args.dry_run)
    if run_status == "create":
        created += 1
    elif run_status == "update":
        updated += 1
    else:
        unchanged += 1

    if args.prune and target_dir.exists():
        reserved = {"run.md", "_workflow_index.json", "README.md"}
        for path in sorted(target_dir.glob("*.md")):
            if path.name in reserved:
                continue
            if path.stem in expected_command_names:
                continue
            content = path.read_text(encoding="utf-8")
            if GENERATED_MARKER not in content:
                continue
            if args.dry_run:
                print(f"[DRY-RUN] delete {safe_rel(path, script_root)}")
            else:
                path.unlink()
            deleted += 1

    mode = "DRY-RUN" if args.dry_run else "APPLY"
    print(f"[{mode}] source={safe_rel(source_dir, script_root)} target={safe_rel(target_dir, script_root)}")
    print(
        f"[{mode}] workflows={len(workflows)} created={created} updated={updated} "
        f"unchanged={unchanged} deleted={deleted}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
