#!/usr/bin/env python3
"""Wave-5 wrapper generator (roadmap item 6e).

One manifest (`wrappers_manifest.json`) → per-vendor critic wrappers in each
vendor's native format, so the 3 critics × N scaffold vendors no longer need
hand-sync. Claude Code is the validated reference/donor and is NOT generated
(it stays hand-maintained at `.claude/agents/`).

Usage:
  python3 generate_wrappers.py            # write/overwrite all scaffold wrappers
  python3 generate_wrappers.py --check    # exit 1 if any on-disk wrapper drifts from the manifest

Vendor formats (verified against primary docs, Task 080/081):
  gemini      .gemini/agents/<name>.md            Markdown + YAML frontmatter
  codex       .codex/agents/<name>.toml           TOML
  cursor      .cursor/agents/<name>.md            Markdown + YAML frontmatter
  antigravity .antigravity/agents/<name>/agent.json  JSON (custom-agent form)
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]          # repo root
HERE = Path(__file__).parent
MANIFEST = json.loads((HERE / "wrappers_manifest.json").read_text())
ENUM = MANIFEST["convergence_enum"]

SCAFFOLD_MD = ("<!-- ⚠️ SCAFFOLD (generated by skill-parallel-orchestration/scripts/generate_wrappers.py, "
               "roadmap item 6e) — NOT yet validated on a real runtime. Edit wrappers_manifest.json, "
               "not this file. See references/{ref}. -->")
SCAFFOLD_HASH = ("# ⚠️ SCAFFOLD (generated by skill-parallel-orchestration/scripts/generate_wrappers.py, "
                 "roadmap item 6e) — NOT yet validated. Edit wrappers_manifest.json, not this file. "
                 "See references/{ref}.")


def body_lines(c, readonly_clause):
    """The shared wrapper body as a list of '- ' bullet strings + intro.

    The vendor-specific `readonly_clause` is added only when the critic has no
    `evidence` clause of its own — the evidence clause (security/performance)
    already establishes the read-only contract, so adding the generic one too
    would be redundant.
    """
    intro = f"You are the **{c['persona']}** teammate. " + c["sot_clause"].replace("{sot}", c["sot"])
    bullets = [c["scope"]]
    if c["evidence"]:
        bullets.append(c["evidence"])
    elif readonly_clause:
        bullets.append(readonly_clause)
    bullets.append(f"{c['return']} Emit the `Convergence signal`: `{ENUM}` ({c['bikeshed']})")
    return intro, bullets


def gen_gemini(c):
    intro, bullets = body_lines(c, "The `tools` whitelist above is read-only (no write/shell) — you report findings; the orchestrator applies fixes.")
    fm = [
        "---",
        f"name: {c['name']}",
        f"description: {c['description']}",
        "tools: [read_file, read_many_files, search_file_content, glob]",
        "# ⚠️ tool names are the read-only subset — verify against the live Gemini tool registry during validation.",
        "model: inherit",
        "---",
    ]
    body = "\n".join(fm) + "\n\n" + SCAFFOLD_MD.format(ref="gemini-cli.md") + "\n\n" + intro + "\n\n" + \
        "\n".join(f"- {b}" for b in bullets) + "\n"
    return ".gemini/agents/" + c["name"] + ".md", body


def gen_cursor(c):
    intro, bullets = body_lines(c, "`readonly: true` is set above — you analyze and report, never write. The orchestrator applies fixes.")
    fm = [
        "---",
        f"description: {c['description']}",
        "model: inherit",
        "readonly: true",
        "is_background: false",
        "---",
    ]
    body = "\n".join(fm) + "\n\n" + SCAFFOLD_MD.format(ref="cursor.md") + "\n\n" + intro + "\n\n" + \
        "\n".join(f"- {b}" for b in bullets) + "\n"
    return ".cursor/agents/" + c["name"] + ".md", body


def gen_codex(c):
    intro, bullets = body_lines(c, 'You are read-only (`sandbox_mode = "read-only"`); the orchestrator applies fixes.')
    instr = intro + "\n\n" + "\n".join(f"- {b}" for b in bullets) + "\n"
    lines = [
        SCAFFOLD_HASH.format(ref="codex-cli.md"),
        f'name = "{c["name"]}"',
        f'description = "{c["description"]}"',
        'sandbox_mode = "read-only"',
        'developer_instructions = """',
        instr.rstrip("\n"),
        '"""',
    ]
    return ".codex/agents/" + c["name"] + ".toml", "\n".join(lines) + "\n"


def gen_antigravity(c):
    intro, bullets = body_lines(c, "This custom agent is review-only — report findings; the orchestrator applies fixes.")
    system_prompt = intro + "\n\n" + "\n".join(f"- {b}" for b in bullets)
    obj = {
        "_scaffold": "⚠️ generated by generate_wrappers.py (item 6e) — NOT validated; edit wrappers_manifest.json. See references/antigravity.md. Antigravity is dynamic-first; this is the static custom-agent (agent.json) form.",
        "name": c["name"],
        "description": c["description"],
        "hidden": False,
        "system_prompt": system_prompt,
    }
    return ".antigravity/agents/" + c["name"] + "/agent.json", json.dumps(obj, indent=2, ensure_ascii=False) + "\n"


GENERATORS = {"gemini": gen_gemini, "codex": gen_codex, "cursor": gen_cursor, "antigravity": gen_antigravity}


def emit():
    out = {}
    for vendor in MANIFEST["vendors"]:
        for c in MANIFEST["critics"]:
            rel, content = GENERATORS[vendor](c)
            out[rel] = content
    return out


def main():
    check = "--check" in sys.argv
    out = emit()
    drift = []
    for rel, content in out.items():
        p = ROOT / rel
        if check:
            if not p.exists() or p.read_text() != content:
                drift.append(rel)
        else:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content)
    if check:
        if drift:
            print("DRIFT — these wrappers differ from the manifest (rerun generate_wrappers.py):")
            for d in drift:
                print("  " + d)
            sys.exit(1)
        print(f"OK — all {len(out)} scaffold wrappers match the manifest.")
    else:
        print(f"Generated {len(out)} scaffold wrappers ({len(MANIFEST['vendors'])} vendors × {len(MANIFEST['critics'])} critics). Claude Code excluded (hand-maintained reference).")


if __name__ == "__main__":
    main()
